### ISSUE TITLE
Pixelate OSX

### ISSUE THREAD

**Issue by randygrolemund** [greenshot/greenshot#110]
Good morning,

I bought your app a few months ago through the Apple App Store. At first, everything worked fine... until I went to use the pixelate feature. It keeps hiding the pixelate box behind the image. Sometimes I can minimize the app, then maximize and it shows up. Most of the time (90%+) it does not work at all. It's just on OSX, the windows version works (but I didn't buy that version).

Do you have any suggestions? I'm running the newest OS, on a brand new Macbook Pro.

I'm not sure if you guys are even developing this application anymore (I hope so), but please add a feature to remove the prompt to save. I normally screenshot and paste in to something else. I rarely save, so the prompt gets annoying when working with lots of screenshots.

I seriously love this app.... just those 2 things, and I'll be a happy camper! :)

Screenshot of me trying to select text to pixelate:
![image](https://user-images.githubusercontent.com/8581255/51606936-e5e0e080-1ed8-11e9-9b4d-7defbddced9b.png)

Screenshot after minimize and then maximize:
![image](https://user-images.githubusercontent.com/8581255/51606969-f85b1a00-1ed8-11e9-9914-9aef53d803c6.png)

**Comment by Lakritzator** [comment]
I'm really sorry, this is not the place for OSX issues and I cannot help you with that.
This is the place to report code issues, for developers, in the **Windows** version of Greenshot.
You should have gotten a template telling your this, and in the application there should be a link to report issues.

Please report your issue here: https://greenshot.atlassian.net/projects/MAC
I cannot forward the information there.
