### ISSUE TITLE
PGP signatures

### ISSUE THREAD

**Issue by Robespeler** [greenshot/greenshot#111]
I came from ShareX software. The same issue is there.
I think true open source project must have developers pgp signations with github releases
Why I want to use your product? Why not joxi or lightshot?
Please, we need it.

**Comment by Lakritzator** [comment]
Do you mean we should sign our binaries with PGP? I'm not 100% sure if I understand you correctly.

We actually have a more official way of signing Greenshot, we are using an official code signing certificate (which again is registered with my name): https://getgreenshot.org/faq/is-greenshot-clean/

Why should we add PGP, you say "we need it", please explain why.

**Comment by Robespeler** [comment]
Thank you for your answer and maybe I am some sorry. I am newbe in this way. Since I know about open source and pgp signations I thought that it is the one way solution. I didn't know about code signing certificate system in your product. 

Explain, how can I check the downloaded file is signed?

The main problem, I think, is compromising the file
1) If somebody compromised official site
2) Or hacker change file on the fly during download (by DNS attack for example)

P.S.
By the way, I have tried Greenshot and it is fairy great. I like it.

**Comment by Lakritzator** [comment]
If you download Greenshot, preferably from our site, you can check if it's genuine by right-click -> properties -> digital signatures. And my name "Open Source Developer, Robin Krom" should be mentioned. (Maybe in the future Robertus Krom, due to legal issues as this is on my travel documents).

When installing, Windows should not warn you but just mention that it's from us.
It's an official Windows way of signing executables, and is directly supported by the OS, without the need to install additional software to check. It's very secure, and costs us money!

To see the difference between signed and not signed, check this out and compare the before and after screenshots:
https://mkaz.blog/code/code-signing-a-windows-application/

I'm closing this, as I find the code signing a much better solution than adding PGP which needs additional software on the side of our users.

**Comment by DumbJoe** [comment]
> I'm closing this, as I find the code signing a much better solution than adding PGP which needs additional software on the side of our users.

If Code signing is a digital certificate, well I can say for certain that I've hex edited an exe file, also digitally signed, but the certificate still show as coming from them, when it should be gone because the file has lost its integrity....

Also on this point, I take it that hashes are also out of the question too? As that also requires the end user to have a hashing program or a way to verify the hashes are indeed identical and for a non-tech savvy person, that could be difficult to achieve....and thus they prefer a quicker more user friendly method....

**Comment by Lakritzator** [comment]
Did you try modifying our executable, and check if it's still a valid code signEd file afterwards?

We pay for this code signing, and it's build into windows, if you can make proof to your claim, you will get a lot of attention from microsoft.

**Comment by DumbJoe** [comment]
Just to clarify, the image below is the digital certificate tab of a digitally signed file right?
![pic](https://i.imgur.com/MZM4iVg.png)

And if I were to edit it in some way, like hex editing it randomly as mentioned above, this tab shouldn't exist and would appear like this other file which isn't digitally signed as the tab is missing for it:
![pic](https://i.imgur.com/QgTaYJC.png)

 Yes?

**Comment by Lakritzator** [comment]
Code signing will add a digital signature yes, for Greenshot it looks something like this:

![image](https://user-images.githubusercontent.com/708125/67749414-6bc42600-fa2d-11e9-9ee8-052e82d6cc28.png)

If you look at the details of the signature, you will see this:

![image](https://user-images.githubusercontent.com/708125/67749473-84ccd700-fa2d-11e9-9165-2bb8d0fcc0a4.png)

Gültig is German for valid.

If one would run the installer without modification it would say that I (Robin Krom) provided the file,and there would not be a red warning.

But modifying the doesn't remove the signature, the signature will still be there, but it will be invalid!
The details will show something like this:
![image](https://user-images.githubusercontent.com/708125/67749555-ac23a400-fa2d-11e9-895d-ed85f9ad5c88.png)

"ungültig" is German for invalid.

Additionally: If you would run this installer, the one after modifying, you get an error with something like "the provider cannot be verified".

Just try for yourself with the Greenshot installer.

If there is NO digital signature, you would also get a warning.

See also here: https://www.sslsupportdesk.com/how-to-verify-a-digital-code-signing-signature-in-windows/

**Comment by Robespeler** [comment]
I suggest microsoft can themself sign file with your certificate in theory to fake your own. If somebody powerfull seize your site or server it will make sence.

Nowdays we can trust nobody. They logging every step throuth ip, email, email confirmations, notifications, cookies, browser canvas and etc.
I also remid true crypt story and microsoft github story.

Mass user maybe appreciates signed certificate but as for me I am not appreciate you paying money to microsoft. I am appreciate your product and your doings.

**Comment by Lakritzator** [comment]
@Robespeler for me it sounds like you are basing paranoia on reduced knowledge and incomplete facts. I do understand that one should not trust anything & anybody, but trusting nobody would lead to a very difficult life.

First:
The code-signing certificate we use is not from Microsoft, we don't pay them anything. We are using a Certificate Authority (CA) called Certum and the process is exactly like "SSL" Certificates. The certificate itself can only be created once. If someone tampers the process of generating a certificate in the name of a CA, which is **not** similar to someone stealing my certificate, the CA needs to invalidate their root CA. This would be a huge price to pay, and reduce their day to day business in such a way that the probably go bankrupt.
The process of getting a code signing certificate involves ME providing them with proof that I am who I say (showing identity card, copies of recent bills & payments etc)

Second:
If a powerful company, like in your example, would seize control and this would be public knowledge, they would be sued and also have a reputation impact... this would be measurable in stock prices and future customer binding. Don't think lightly of the impact, a company like Microsoft would move heaven and earth to prevent something like that.

Question:
I know the true crypt story, but what do you mean with the "Microsoft github story"?
What is not to trust there?

To answer your last remark, without code-signing our installer with a certificate every person using our installer would be confronted with a RED dialog with warnings. We like to prevent this.

What we CAN do to improve trust, is to post our certificate thumbnail, this is a code-sequence which one can manually compare to detect the download originates from us, which is on top of "it's signed by a valid certificate".

The thumbnail is: 6d fa 88 fe db a9 57 85 5d b9 38 b3 80 82 37 8f 14 c7 cc cc

**Comment by DumbJoe** [comment]
@Lakritzator 

Ahh, I see, it's one more step to verify if the file is modified or untouched on the receiving end - I had always thought if the file lost that tab, then that means it's not legit regardless if you downloaded it correctly or not unless the author provided a hash to check with or you upload the file to virustotal that will scan and hash the file for you and find out since when it was first discovered and hopefully see some comments about the file....
![pic](https://i.imgur.com/pjHpFik.png)

But what about in the case of this(it seems editing some parts remove the tab completely whilst other parts leave the tab in place): 
![pic](https://i.imgur.com/2RX7ZfI.png)

when it should be showing this like you said:
![pic](https://i.imgur.com/LropQK8.png)

when you modify the file?

> Nowdays we can trust nobody. They logging every step throuth ip, email, email confirmations, notifications, cookies, browser canvas and etc.

Is this coming from all those telemetry updates of windows 7, 8, 8.1 and 10...?

> I also remid true crypt story and microsoft github story.

Don't know about the true crypt story but I know a bit about the microsoft github story if that is the story where they bought out github and gave everyone free pro upgrades to even the free users that everyone thought would make github shite after they bought them out? This was also suppose to replace their own code repository, forgot it's name, but they weren't doing so well....
