### ISSUE TITLE
Painting, Right Click Menu

### ISSUE THREAD

**Issue by lollilol** [greenshot/greenshot#130]
1. Painting: Would be nice to have painting integrated in Greenshot, like in lightshot.
2. Right Click Menu: When i deselect the "Select destination dynamically" feature in the destination tab, and take a screenshot, it instantly does this, what i selected. This is perfect! What would be nice though that when you right click, while holding down left mouse button (selecting the area to screenshot) opens up the right click menu from "select the destination dynamically" to open the picture for example in paint.net or something like this.
Hope you understand it, im not native english speaker. Be free to ask, if you dont get it!

**Comment by Lakritzator** [comment]
I'm not sure what you mean with both things, I can imagine but it doesn't make sense for me to guess what you want.

1: Greenshot already has an editor
2: You mean that the capture by default goes to the destination you "hardcoded", but you want a way to get the dynamic destination picker?

You ignored the huge notice when creating this issue, this repository and the issues are for coder only! Please create your feature requests on https://greenshot.atlassian.net otherwise they will be overlooked here. I'm closing this issue, my apologies when this is rude but we have more than 10 users, and need to have a workflow for this.
