### ISSUE TITLE
GIF-Animated capture screen zone

### ISSUE THREAD

**Issue by kzelda** [greenshot/greenshot#154]
Please can you add this feature : capture an animated GIF image from video played on screen

**Comment by Lakritzator** [comment]
For feature requests we have our JIRA, as is specified in the template when you create an issue.

Closing this.

**Comment by sdudnic** [comment]
no, really, what an answer... is there a way or not to capture a gif movie from the screen using greenshot?

**Comment by Lakritzator** [comment]
@sdudnic: There is not a way, so this is why he requested this as a feature.
It wasn't a question if it was already there, he wanted to have such a feature.

And I gladly talk about such features, but I need a proper description and currently we track our bugs & features on our JIRA.

I don't want to sound harsh, but do realize we create and support this in our free time, so we decide how, where and when we support this. Otherwise we have topics running all over the place. We use GitHub for developers that want to contribute code, so we have short communication ways when code is involved.

Btw. if you need to capture a movie to a gif, I can advice https://www.screentogif.com/
