### ISSUE TITLE
qucik question about current status.

### ISSUE THREAD

**Issue by spacecabbie** [greenshot/greenshot#159]
Hi and hello,

Just wondering if the project is still allive since the windows release is from 2017.
I only use linux headless so din't have change to look at that version.

So in short is windows support dropped ? Just behind. Or only maintenance updates? ty,

**Comment by wookiefriseur** [comment]
Development of the new version looks alive to me: [https://github.com/greenshot/greenshot/commits/develop](https://github.com/greenshot/greenshot/commits/develop)

As far as I understand it's a migration to new library versions with major version changes. This might also be the reason why you don't see any new releases of the "old" stable version.

**Comment by spacecabbie** [comment]
Oh yes i am more or less referring to windows as i have not had the chance to test or build anything from source. I figured posting a quick question would be quiker

**Comment by jklingen** [comment]
Hi there,
yes, we're still alive ;-) As @wookiefriseur mentioned, Greenshot indeed needs some overhaul under the hood. Also, lately all of us are a little short of time due to our full-time-jobs, families, homes etc., which is why we cannot invest as much of our spare time into this open source project as we used to in the past.
So: no - Windows support has not been dropped, but things are progressing slowly ATM. I hope this anwers your question.

**Comment by spacecabbie** [comment]
Awsome good to hear family always goes first  👍.

May I suggest a just a quick news post or something on the website ? to avoid people thinking the same. I was in customer support for 10 years. It helps keeping the people attached to the programm. Thanks for the response and happy Xmas and new year.
