### ISSUE TITLE
New version after more than 2 years

### ISSUE THREAD

**Issue by Neustradamus** [greenshot/greenshot#163]
Since 2017-09-13 (At this time: 2 years, 4 months, 15 days), there are no updates.

It is possible to have new builds?

Thanks in advance.

**Comment by Lakritzator** [comment]
Yes, it is possible.

**Comment by Neustradamus** [comment]
Already done?

Please do not close a ticket before solution.

**Comment by Lakritzator** [comment]
Greenshot is free and open source, provided "as is". We are actively developing on a new version, as should be visible in the commits. A new version comes when it comes, we have no schedule yet, as me and another developer have a kid and we all have jobs so unfortunately we do not always have time.

If you like to speedup the process, you can contribute by:
* Providing us with a code-signing certificate, this costs us money and time.
* Help coding and supply pull-requests.
* Answer issues in our Jira or here, there are **many** low quality issues which need more information or the user needs to be instructed what to do. It also could need grouping and prioritizing.
* Sponsor us, so we can free up more time.
* Sponsor us, so we have the right hardware to develop (I need a high-DPI Windows laptop with >=16GB RAM and a good CPU)
* Do not ask questions which do not add much, and have me spend time on them instead of going forward.

But you are right, we should write a blog post about what we are doing and maybe promote the ways people can support us. I will start writing one...

An example is GitHub Sponsorship, you can use it directly from here.
Or https://opencollective.com/greenshot

I've closed your issue as it doesn't add anything, there is no bug report or feature. Besides you ignored the templates, and the fact that the issues here are actually for developers.

**Comment by mischlrebl** [comment]
Is the list of possible contributions complete?
I would be able to test new versions from time to time. But they have to been built already.
As far as I can judge the option 'check for unstable updates' in the expert tab does not bring any newer builds, but I might be wrong.

**Comment by Lakritzator** [comment]
@mischlrebl You are not wrong. There are some builds, but so extremely volatile that I don't want people to use them as it would only cause an endless stream of questions / discussions.
I also would need to explain how people can remove them, I rather spend the little time I have to come forward instead.

**Comment by Lakritzator** [comment]
I've made a build, so people can have a look at the current state.
https://github.com/greenshot/greenshot/releases/tag/v1.3.38

Still lot of things to do, but at least it should not be extremely volatile.

**Comment by Neustradamus** [comment]
@Lakritzator: Have you a roadmap for the STABLE version?

**Comment by Lakritzator** [comment]
You can follow our 1.3 project https://github.com/greenshot/greenshot/projects/2

**Comment by Neustradamus** [comment]
Today: 2025-05-14: The status is same than initial ticket date: 2020-01-27.

Now, since 2017-09-13: 7 years, 8 months, 1 day) without a new build.

**Comment by Neustradamus** [comment]
@jklingen: Important to specify tickets about it, security is very important.

**Comment by FF-Brown** [comment]
@Neustradamus We can all see the Posted date

**Comment by jklingen** [comment]
FYI: we released a signed build (1.3.281) of the current state and are aiming to publish a release candidate soon.

For details, please see our latest blog post [Working towards Greenshot 1.3](https://getgreenshot.org/2025/05/20/working-towards-greenshot-1-3/).

And no, cross-posting _really_ didn't help 😏 the timing is just a coincidence.

**Comment by Neustradamus** [comment]
@jklingen: Thanks for your recent unstable build!

But a lot of people or companies would like a new stable build, a 1.4.x.x, it is for this, currently, it is always 1.2.x.x but badly unsecure...

**Comment by Neustradamus** [comment]
@jklingen: When have you plan the first Greenshot 1.4.x stable version?

1.3.x branch is for development (unstable builds).

**Comment by Christian-Schulz** [comment]
@Neustradamus  https://github.com/greenshot/greenshot/releases/tag/v1.3.292 is not marked as `unstable` or `pre-release` , so this is currently the `stable` version.

**Comment by Neustradamus** [comment]
@Christian-Schulz: I think it is a mistake, 1.3 is an unstable branch.

**Comment by jklingen** [comment]
>  I think it is a mistake, 1.3 is an unstable branch.

No. Greenshot 1.3.202 is the latest stable version.
