### ISSUE TITLE
Is there any roadmap for Greenshot 2.x available?

### ISSUE THREAD

**Issue by chrgraefe** [greenshot/greenshot#166]
This GitHub repository is for developers, if you want to request a feature for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/FEATURE/issues/filter=allopenissues

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Lakritzator** [comment]
Actually due to the fact that we cannot support Windows 7, I wanted to release Greenshot 1.3 in the coming month(s) with some fixes and a few new features. For those companies who want to afford the extended Microsoft support, they at least can enjoy a current Greenshot...

What do you mean with a roadmap?

**Comment by jklingen** [comment]
@chrgraefe you might want to have a look at [this one](https://github.com/greenshot/greenshot/issues/163#issuecomment-579100499)

**Comment by chrgraefe** [comment]
Thanks for your effort!
