### ISSUE TITLE
Anti-Virus Quarantined installer as Heur.AdvML.B

### ISSUE THREAD

**Issue by tmknight** [greenshot/greenshot#173]
Been seeing this since the latest round of unstable releases these past weeks.  Both with Norton and Defender.  I am downloading from github.  I haven't had issues with other installers from github.  I think it's a false-positive (I've submitted to Symantec).  Anyone else experiencing this for Greenshot installers?
![image](https://user-images.githubusercontent.com/548588/76212226-63030e00-61de-11ea-93d1-89101b3e815c.png)

**Comment by Lakritzator** [comment]
I assume this is a false-positive, as some of the technologies used by Greenshot are most likely usable by virus / malware software too. Because we used to ode sign our installer, this might have changed the reputation which is currently due to missing code signing not the case.

Greenshot builds are build on a Azure DevOps Windows build "agents", not on our private system. A build agent is reset before each build. The chance that a virus is infecting our installer is very little.

What might be the case, is that one of the libraries we use is infected. I'm trying to integrate virus total into our build, so we can detect such things in more details. Also providing a .zip will help to identify the file causing the hit.

I didn't look into Heur.AdvML.B yet, I don't even know what it supposed to do.

**Comment by tmknight** [comment]
Agreed on likely false-positive and that MS would be scanning and catch it.  Though, thanks for looking just the same.

**Comment by Lakritzator** [comment]
I didn't understand the part of MS, MS will not be scanning it, or catching it.
 
But as soon as Greenshot has a code-signing certificate and the first X people are using it, confirming there is no harm, the virus scanners will suddenly stop.

Also if false positives are send to symantec, via https://symsubmit.symantec.com/, they will also go away. But doing this for all scanners and with every version, is a lot of work.

Anyway, thanks for reporting this, I will check if I can get some more details.
