### ISSUE TITLE
Plans/timeline for the editor?

### ISSUE THREAD

**Issue by KillyMXI** [greenshot/greenshot#185]
I'm having trouble to get an answer in the place of origin, so I have open this issue in hope to finally have a bit of maintainers attention!

There is an interest to have a certain feature in the editor. I would like to step in and implement it.

But, because the existing editor is marked as legacy and there is an ongoing work to move to WPF, I'm not sure it makes sense to work with the existing editor. I also see a couple of experimental projects that don't seem to be any close to be shipped, but if there is something going on under the radar - that might also be helpful to know.

So, I would like to know your plans and estimates for the editor.

----

https://greenshot.atlassian.net/browse/FEATURE-84 - no answer for 3 weeks. You better do away with Jira if you provide no support there. So far it looks like writing to /dev/null.

https://github.com/greenshot/greenshot/issues/25#issuecomment-603229039 - no answer either.

**Comment by Lakritzator** [comment]
I'm sorry you can't wait... but honestly, I'm ill and for the last 4 weeks we have to entertain a 4yo while the kindergarten is closed. Work didn't stop either, and groceries etc take much more time. In fact my son was banging on the door, while I started to answer this,  as he can't sleep... (8:40 in the evening) So I'm now sitting in his room next to his head typing this before I go to bed...

> You better do away with Jira if you provide no support there. So far it looks like writing to /dev/null.
You better stop nagging, Greenshot is free so why do you assume you got the right for support or a certain response time? Greenshot is a free time project, and I work on it when I have time and energy, and as time is short I rather do something fun or small. If you like things to go faster, sponsor us e.g. on open-collective or me here at github, this can make me work less and have more time for Greenshot.

Also do you really think that writing all over the place makes me come out of my bed, or interrupt my playtime with my kid, or that I answer during the work I also have to do to make a living? I see all comments and issues, in Jira and Github come by, sometimes I can't answer all.

Don't get me wrong, I really like to have some help to get the zoom working.
I saw your JIRA, comment and issue... answering takes a lot more time than a simple bug.
My priority is to get the 1.3 release out of the door, which is already costing me all my leftover energy.

As Greenshot 1.3 might still be used many years by people not liking 2.0 due to reasons yet unknown (dotnet core, size, looks), it depends on the effort one needs to put into a zoom, but it might make sense. As the editor is a lot of manual painting, I'm not really sure if it would be so easy. But you are welcome to propose a solution!

We started working on a WPF editor in a private repo, as other people steal our code. On a scale from 0-100 (where 100 is finished) I would say we are at 5...

Hope I wasn't to harsh, but you annoyed me.

P.S.
You know what effort Greenshot 2 is? https://www.openhub.net/p/greenshot
I wrote most projects here for Greenshot 2: https://github.com/dapplo see an analysis here: https://www.openhub.net/p/dapplo

Most of it is a one person job...

Best wishes,
Robin

**Comment by KillyMXI** [comment]
I'm sorry for being annoying.
There are many possible reasons for silence and I can't tell the difference before someone actually break it. You better also try to understand how it looks from outside.

People often perceive my actions as impatient and demanding. While in fact I understand there are various possible situations and I can't demand for an immediate solution. Neither I want to. But I highly value communication. Simple acknowledgement can clear up the situation quite a bit, even before you will be ready to explain all you might want to.

> one person job

I interpret this very common argument as either a personal choice or a lack of exposure or interest for the project, or inability to lay down work in a way so other people will be ready to pick it up and contribute (this will mean to be a manager more than a programmer sometimes, not everyone's cup of tea).

In either case it's not helpful to know. I'm here to contribute, address some users demands and make them happier with your app, while possibly free you up for other things. In this situation, pointing at how you are hard-working alone - is not a good start, it tells a different story from what you've tried to say just above it.

Anyway, thank you for the answer. I'm now more convinced to proceed.

**Comment by KillyMXI** [comment]
The moment I was ready to make a PR - there is a work started at the same place.
Let's see how these features will live together...

**Comment by jklingen** [comment]
Never mind - my changes are minimal, should be easy to merge :)

**Comment by Lakritzator** [comment]
Closing this with a huge ❤️ towards  @KillyMXI who came through an build a really awesome zoom feature into our editor.
