### ISSUE TITLE
GUI - Info/FAQ about translation of language files

### ISSUE THREAD

**Issue by bovirus** [greenshot/greenshot#199]
This GitHub repository is for developers, if you want to request a feature for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/FEATURE/issues/filter=allopenissues

**Is your feature request related to a problem? Please describe.**

Is there a specific code to add to langauge file text a forced CR/LF?

Why in Github the Italian language is not aligned as number of string to Github English language file?

When you update English language in github with new strings also do you update the other language files to maintain all languages files aligned? It’s importnat?

Why the latest beta 1.3 of Greenshot program one times installed has English/Italian language files with more strings (as number) than the same language files available in Github?

Is there a relation between language files in the program and language files in Github?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jklingen** [comment]
Yeah, our translation process is not comletely straightforward at the moment :frowning_face: our plan is to use a decent platform for translations in future, but for now it is as it is.

> Is there a specific code to add to langauge file text a forced CR/LF?

Even though I assume that the sort of line breaks wouldn't matter, I am not sure, so if in doubt it is always better to keep the line break encoding as it was before. Every decent text editor (e.g. Notepad++) has an option to encode line breaks as needed.

> Why in Github the Italian language is not aligned as number of string to Github English language file?
> When you update English language in github with new strings also do you update the other language files to maintain all languages files aligned? It’s importnat?

No, we don't. If Greenshot does not find a string in the translation, it uses the english string as fallback. So, in order to find strings that are missing in a translation, the translator would have to diff the translation file against the en-US file.

> Why the latest beta 1.3 of Greenshot program one times installed has English/Italian language files with more strings (as number) than the same language files available in Github?

This is because the 1.3 release is being prepared on a [separate branch](https://github.com/greenshot/greenshot/tree/release/1.3), that does not include many changes that have happened in [develop](https://github.com/greenshot/greenshot) (e.g. all the editor-related strings have been [moved to a dedicated place in develop](https://github.com/greenshot/greenshot/tree/develop/src/Greenshot.Addon.LegacyEditor/Languages), but not in the 1.3 branch - which is probably the reason that there more strings in the latter). This also means that we need to back-port your changes to the 1.3 translation file, if we want to have it included in the upcoming release. :confused: 

> Is there a relation between language files in the program and language files in Github?

Yes, I hope the answers above cleared up on the relationship.

**Comment by bovirus** [comment]
@jklingen 

Thanks for the quick reply.
Now is more clear.

Please when you can merge PR about Italian language.

How can check the translation in place using develeper branch?
Where can I find an installer for version of developer branch?

My proposal is also in English language when you string with multi-period to increase tthe clearance add a CR/LF for each period.

Thanks.

**Comment by jklingen** [comment]
@bovirus I have just merged your updates and backported them into our 1.3 branch, so that they will be included in the next release. Thanks again for your contribution :+1: 

There is no recent release of the develop branch, but I gave it a try locally and everything seemed to work fine with the updated translation.

I agree, the XML files are not nice to edit. I hope we'll be able to set up a proper solution soon.
