### ISSUE TITLE
Can't edit shortcuts

### ISSUE THREAD

**Issue by Ansem93** [greenshot/greenshot#202]
**Describe the bug**
Can't edit shortcuts:
![immagine](https://user-images.githubusercontent.com/6626218/80475466-33a09000-8949-11ea-9901-c0c20816154c.png)
I can select any of the black voice :(

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.3.1

**Comment by Lakritzator** [comment]
I'm confused, you are reporting a ShareX issue in the Greenshot project!?

**Comment by Lakritzator** [comment]
I'm pretty sure this was falsely reported, closing this.

**Comment by Korb** [comment]
I also believe this issue was created in error, but I don't want to create a new issue with the same title. I'm a new Greenshot user, and neither in the application menu nor in the **Settings** window, which is opened with the **Preferences** command, did I find anything resembling **Hot keys** / **Hotkeys**, **Shortcuts**, **Keyboard shortcuts**, **Shortcut Mapper**, **Manage Extension Shortcuts**, **Keyboard reference**, etc.

I support the proposal to add a corresponding feature to the application, including conflict checking.
