### ISSUE TITLE
Add CTRL+Wheel to new zoom feature

### ISSUE THREAD

**Issue by nicorac** [greenshot/greenshot#208]
As already discussed [here](https://github.com/greenshot/greenshot/pull/201#issuecomment-627220968) with @KillyMXI, CTRL+Wheel is something most users expect to use to zoom in/out the edited object.

CTRL+Wheel is so widespread that becomes such a natural action, and all the softwares I use day-by-day have it: Firefox, Chrome, paint.NET, GIMP, Kdenlive, Shotcut, Notepad++, Office, LibreOffice, VisualStudio, VSCode to name a few.

Zoom feature was a great addition, I hope you could this missing piece to GreenShot 😉

**Comment by Vig2OOO** [comment]
Or better yet, an option for just mousewheel zoom (without the use of the CTRL key).

**Comment by nicorac** [comment]
> Or better yet, an option for just mousewheel zoom (without the use of the CTRL key).

Do you mean that Wheel alone will zoom in/out?
Never seen that...

The most common behavior (AFAIK) is:
- Wheel: scroll up/down
- CTRL+Wheel: zoom in/out
- SHIFT+Wheel: scroll left/right (more and more programs are using this combination)

**Comment by Vig2OOO** [comment]
> > Or better yet, an option for just mousewheel zoom (without the use of the CTRL key).
> 
> Do you mean that Wheel alone will zoom in/out?
> Never seen that...
> 
> The most common behavior (AFAIK) is:
> 
> * Wheel: scroll up/down
> * CTRL+Wheel: zoom in/out
> * SHIFT+Wheel: scroll left/right (more and more programs are using this combination)

Yes, that is what I mean, so going for the keyboard would be unnecessary, but give the user the option to use the mousewheel alone to zoom or in combination with an operator like the CTRL key.

**Comment by KillyMXI** [comment]
> * Wheel: scroll up/down
> * SHIFT+Wheel: scroll left/right (more and more programs are using this combination)

And that's exactly how it currently works in Greenshot. I see no reason to change this. So CTRL+Wheel is the most natural choice.

I also want to mention here a proposal by @mischlrebl : Drag canvas with modifier key + mouse, as an alternative to scroll.
That might be done as a part of the same effort.
The version of Acrobat Reader I have doesn't have this behavior though. I'll have to look for more app examples.

**Comment by Lakritzator** [comment]
There is always a discussion that everybody wants different keys! 🤷 

I agree with what @KillyMXI said, and I will **currently** not like to see any settings to change the behavior as we don't have place in the current settings UI. In version 2 I've redesigned the UI to be able to handle a lot more settings.

The dragging is a good idea, but it does need to fit to the already available feature of selecting elements on the canvas. If people want to select multiple items the press shift and start selecting.

**Comment by Vig2OOO** [comment]
Don't have anything set in stone; instead, make it like a program like ImageGlass where the _user_ decides what the mousewheel does.  In other words, make the zoom functions user customizable (assuming that is technically possible).  So if someone wants the zoom function to be via CTRL + Mousewheel, then sure!  If someone else wants to zoom with the mousewheel only (without the use of a modifier key), then sure!  Each user decides what they want.

**Comment by Lakritzator** [comment]
@Vig2OOO like I already mentioned, this might be something we can work on in Greenshot 2 but right now we don't have the space in the settings UI to do so. Let's first work on getting Greenshot 1.3 out in the open.

**Comment by mischlrebl** [comment]
dragging is most often done by space bar + mouse what is very hand and does not interfere existing short cuts in GS (as far as I know)

sorry, I refered the wrong key in my initial comment [here] (https://github.com/greenshot/greenshot/pull/201#issuecomment-627922936): it is the SPACE, not the shift...

**Comment by nicorac** [comment]
> > * Wheel: scroll up/down
> > * SHIFT+Wheel: scroll left/right (more and more programs are using this combination)
> 
> And that's exactly how it currently works in Greenshot. I see no reason to change this. So CTRL+Wheel is the most natural choice.

I agree 👍

**Comment by jolsen71** [comment]
I agree on having the settings configurable by user because my personal preferences seem to differ from the norm.

I like CTRL+WHEEL for zoom, but I prefer ALT+Wheel for left and right and SHIFT as a "speed" multiplier for more aggressive scrolling. 

My reasoning for my personal preference is that makes more sense mnemonically. Generally speaking, capital letters are larger than their lowercase counterparts. The larger capital letters are produced by pressing the SHIFT key. In keeping with that, pressing SHIFT while "wheel"ing would scroll faster (larger position change per wheel rotation) than wheeling alone. I think ALT also makes sense for horizontal scrolling because we're choosing to scroll on the ALTernate axis from the default of vertical.

So my personal preferences are:
WHEEL = scroll up and down (vertical)
SHIFT+WHEEL = faster scroll up and down
ALT+WHEEL = scroll left and right (horizontal)
ALT+SHIFT+WHEEL = faster scroll left and right
CTRL+WHEEL = zoom in and out

So while I'll happily agree the Greenshot's defaults should go with the status quo for best out-of-box UX, I sincerely request that it can be customized for oddballs like me who swim with different strokes.

**Comment by Lakritzator** [comment]
Fixed with PR #282, we decided for now on the CTRL+Wheel
