### ISSUE TITLE
This is actually a security concern rather than bug

### ISSUE THREAD

**Issue by Hardikverma** [greenshot/greenshot#219]
Hey there, I downloaded the executable of the recent 1.3.106 unstable version. When uploaded on virustotal there was Malicious activity detected I don't know if that may because you guys inserted any ads network in it or what but, that's not the issue. But, The Executable was not signed that made me suspicious.

**Comment by Lakritzator** [comment]
Hi,

no worries!
The executable is not signed as certificates cost money, and our previous one expired.
We had some difficulties getting a new one, it's not just money, so the signing is postpone on the unstable builds.
We are actually looking at a solution from signpath.io, but this currently forces us to change the way we build.. due to corona I don't have unlimited time.

Anyway, due to the fact that is wasn't signed there will be more security messages.

This will be fixed later. For now, know that we do NOT EVER build Greenshot on our personal computers but in the cloud on secure servers. Any malicious code which is detected is most likely due to the fact that I have written low level code for Greenshot to be able to do it's work, which triggers a pattern recognition of the virus scanners.

**Comment by Lakritzator** [comment]
Btw. follow the code signing issue here #264
If we release, do reach out to us if you notice anything.
