### ISSUE TITLE
Greenshot loads forever on triple-screen setup

### ISSUE THREAD

**Issue by borekb** [greenshot/greenshot#28]
When I press `PrtScr` on my home PC which uses 3 monitors (5760x1200 in total), it takes like 40 seconds for Greenshot's UI to come up **for the first time**. Subsequential `PrtScr` work fast as they should.

**Comment by Lakritzator** [comment]
If it wasn't for the fact that it's only at the first time I would imagine you are using an old version and advice you to make sure you are at 1.2.8.12

Please report the bug here: https://greenshot.atlassian.net
This is not an issue tracker for users, but for developers! You didn't read the notice while creating the ticket did you? (guidelines for contributing)

In fact, how did you get here??? There should not be a direct link from our website to github...
