### ISSUE TITLE
Security Vulnerability CVE-2018-1285 for log4net

### ISSUE THREAD

**Issue by Christoph02** [greenshot/greenshot#327]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**

FortiClient found critical issue in log4net.dll

Security Vulnerability CVE-2018-1285 for log4net
Critical
Erscheinungsdatum: 2020-05-11
Empfohlene Aktion:
Downloade und installiere Updates wie angewiesen
Beschreibung:
Apache log4net versions before 2.0.10 do not disable XML external entities when parsing log4net configuration files. This allows for XXE-based attacks in applications that accept attacker-controlled log4net configuration files.
Betroffene Produkte:
Apache log4net
CVE IDs: CVE-2018-1285

**Screenshots**
![grafik](https://user-images.githubusercontent.com/19956485/128492873-bffcd15f-d889-48d6-b809-e05cb7d18c29.png)

**Versions (please complete the following information):**
 - Greenshot version 1.2.10 Build 6 (64 bit)
 - Windows version 10.0.19043

**Additional context**

**Comment by sysadmin0815** [comment]
same here. reported from forti EMS.

**Comment by jklingen** [comment]
Unfortunately we’re currently in a situation where we cannot easily publish a new release due to issues with our code signing certificate. We’re currently in the process of acquiring a new one. Unfortunately, the process takes a while.

Anyone who feels uncomfortable with the situation might want to use the latest 1.3 unstable release from our [version history page](https://getgreenshot.org/version-history/) which uses a more recent version of log4net. However, there is no official release for 1.3 yet.

**Comment by sysadmin0815** [comment]
> Unfortunately we’re currently in a situation where we cannot easily publish a new release due to issues with our code signing certificate. We’re currently in the process of acquiring a new one. Unfortunately, the process takes a while.
> 
> Anyone who feels uncomfortable with the situation might want to use the latest 1.3 unstable release from our [version history page](https://getgreenshot.org/version-history/) which uses a more recent version of log4net. However, there is no official release for 1.3 yet.

Thanks a lot for you answer. I will give it a try!

**Comment by Lakritzator** [comment]
Thanks for the feedback, I am closing this and the fix will be out as soon as I solve #264
