### ISSUE TITLE
Log4shell or log4j RCE vulnerability

### ISSUE THREAD

**Issue by lordzomat** [greenshot/greenshot#352]
After the recent news about CVE-2021-44228 Fortinet reports Greenshot as being affected in some kind.

So is greenshot or the `log4net` port of `log4j` affected by this vulnerability? If so a new 1.2 release could be necessary.

**Comment by Lakritzator** [comment]
I know everybody is running around due to that CVE but it's important to read what a report says.
I can assure you that log4net doesn't have CVE-2021-44228. In fact JNDI is something for Java, and Greenshot runs on .NET.

There is however #327, where we were informed about https://nvd.nist.gov/vuln/detail/CVE-2018-1285.
But I would say the risk is small depending on how Greenshot is installed.
If one could modify the log4net.xml file, they could perform (XXE)[https://portswigger.net/web-security/xxe] attacks.
But to be honest, if they can modify the configuration for log4net, they could also just change the .exe or .dll files, which I would assume to be a lot more critical.

We mitigated the log4net CVE-2018-1285 in 1.3, but are not able to release yet.

**Comment by lordzomat** [comment]
@Lakritzator Thanks for the confirmation. I also found that older CVE from 2018 and already tought that it's a different kind of thing. But I was unsure about the state of log4net in total as it's a port of log4j. So products like Fortinet are no used to scan and that old CVE is popping up for the log4net.dll in the released version of Greenshot causing people to think they are affected.

So I will close the issue.
