### ISSUE TITLE
Clipboard paste not working in all programs in Version 1.3.235

### ISSUE THREAD

**Issue by dingolino** [greenshot/greenshot#372]
I installed the new 1.3.235 Version and the clipboard is not working in all programs In my case HCL Notes, my email program.

1.3.234 is working with no problems.

I make a screenshot
Do some work in the Greenshot Editor
Push in Greenshot Editor the "Copy to Clipboard" button

I can insert the clip into programs like word but not HCL Notes my email program. HCL does not "see" that there is somethin in the clipboard.

Switching back to 1.3.234 is solving the problem.

I tested this on 2 different win 10 machines

Best regards,

Claus

This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture '....'
2. Open Editor
3. Add a line
4. Resize

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Greenshot version
 - Windows version

**Additional context**

**Comment by Lakritzator** [comment]
This is what I feared, it seems HCL can't handle the new format. But the old one is causes major issues (Virtual Box crashing, Windows 11 flashing, Office issues etc.), so I am not going back.

Can you please try with the latest, and enable in the expert settings the "Windows Bitmap" format and try again?

**Comment by Lakritzator** [comment]
![image](https://user-images.githubusercontent.com/708125/152435973-8bfd6b62-c02a-459c-ace1-be9d6414f1cc.png)

**Comment by dingolino** [comment]
Bingo! this is working !!! :-) :-)



What type of "new format" are you using? I want give a  feedback to HCL that they are not able to handle this clipboard format



![image](https://user-images.githubusercontent.com/18245441/152437259-7cba3d27-f125-41de-9575-6486da867bd1.png)

**Comment by Lakritzator** [comment]
The clipboard is a jungle, one could place many formats on it and some are better than others.
Placing everything on it, causes issues as some apps know what they want, others only take what they know, and it might happen that the wrong is used. e.g. some formats do NOT support transparency! So enabling what you did, might cause other issues with other applications... sad but true. If I place a format without transparency on the clipboard, some apps use this, EVEN if a better format is available.

I changed from a certain type of "DIB" (Device Independent Bitmap) to one with different settings, as the old one seems to be causing issues. The old format ne was like saving a BMP file (via on board .NET Framework code), removing the first 14 bytes, and put that on the clipboard. The new one is put together manually, as specified here: https://github.com/greenshot/greenshot/blob/release/1.3/src/Greenshot.Base/Core/DibHelper.cs#L80

But to be honest, I would advice to HCL that they support "PNG" (it's simply a byte stream with a image in the PNG file format). This is also put on the clipboard in the standard with Greenshot, easier to support if you already use images (quite popular format) and supports transparency. Maybe that helps so I do not get any issues reported in ~10 years, with.. who knows, Meta notes (formerly HCL notes, formerly IBM Notes, formerly Lotus notes), like I had 10 years ago with Lotus Notes. 😆

**Comment by Lakritzator** [comment]
Look at this, many clipboard & Lotus notes issues... just a few of them:
https://greenshot.atlassian.net/browse/BUG-79
https://greenshot.atlassian.net/browse/BUG-892
https://greenshot.atlassian.net/browse/BUG-1204
https://greenshot.atlassian.net/browse/BUG-1376

We go back many years, but at least our name didn't change 🤣

**Comment by dingolino** [comment]
> Look at this, many clipboard & Lotus notes issues... just a few of them: https://greenshot.atlassian.net/browse/BUG-79 https://greenshot.atlassian.net/browse/BUG-892 https://greenshot.atlassian.net/browse/BUG-1204 https://greenshot.atlassian.net/browse/BUG-1376
> 
> We go back many years, but at least our name didn't change 🤣

I am using Lotus Notes since the early 90s and I still prefer it over Outlook. Still today I can open a database which was created more than 2 decades ago (that is impossible with Microsoft products). And it is still possible to "save" everything of the program by copy simply the install folder and you can simply copy it back (today with the Multi User, you need to take care a little bit more, and copy 2 directories, the program directory and the user install directory) and HCL Notes will not be deeply integrated into the operating system like all the Windows programs do and even with a uninstall you cannot remove all of the Microsoft components. And so far I am not aware that HCL Notes was or is affected by freaquent security problems like we had recently with Microsoft Outlook.
Over the last 25 years I am not aware that I have lost a single email with Notes. It happend that the "Design" (Schablone) was screwed up by changing to a newer Version, but this could be repaired and fixed easily.

Over all, I hope that I do not have to change from Notes to Outlook until my retirement ...     ;-)

Since Notes was bought by HCL a ongoing development is now visible to the program and I am looking forward that it can prevent exisiting customer from moving to Outlook and hoepfully bring back new or old ones.

Best regards,

Claus

**Comment by ypcyc** [comment]
Hi! Thank you for Greenshot! 
I also faced same issue after upgrading from 1.3.220 to 1.3.235. I confirm that Bitmap checkbox did help me as well :)

**Comment by Frank071** [comment]
Same issue in Thunderbird 91. Enabling WBMP checkbox does the trick here as well. BTW I noticed the option list in that Expert window is pretty small (and the Dutch translation is cut off)
![afbeelding](https://user-images.githubusercontent.com/807403/152689143-f6dae545-9c4e-4990-88cc-c931eb8ba15a.png)

**Comment by Lakritzator** [comment]
@Frank071 Well, this screen was never made to be good looking, it actually should hardly be used 😉 
But thanks for the feedback!

I'm not really happy with the current state of the clipboard, and that is friendly put.
Why can't all those apps not use the PNG format I make available, that is the easiest to use.

I would really like a matrix with all the apps and the formats they support....

**Comment by Frank071** [comment]
Well... I tried to do a bit of research and it looks like Thunderbird 91 doesn't use BMP at all. In https://searchfox.org/comm-central/source/mozilla/editor/libeditor/HTMLEditorDataTransfer.cpp (around line 1207) it is defined which image format is prefered over the other. 
I also checked a recent email I sent after I checked the WBMP option to see what is in the email, and the pasted image was in fact attached as PNG:
![afbeelding](https://user-images.githubusercontent.com/807403/152768349-935a8273-5e42-484d-b834-e1b5641860eb.png)
Could it be that selecting the WBMP format triggers some other behaviour as well?

**Comment by Lakritzator** [comment]
The code there for me reads what formats Thunderbird can paste to the clipboard, and that seems to be PNG, jpg and gif.
But okay, I didn't check the whole code yet.

The format Thunderbird would use in an email, is most likely PNG as this is a fairly efficient format without losing quality. I am not surprised that they do not send a non compressed bitmap via an email. 😉 

Greenshot will place all checked formats on the clipboard, by default one of them is PNG. I somehow expect that Thunderbird does **not** accept PNG, which is weird because it uses it when pasting but I have seen weirder. I wish it would...

**Comment by Frank071** [comment]
I tried to dig deeper in the code of Thunderbird but that has not resulted in anything yet. 

But since, like you, I can't imagine TB to expect a BMP (especially not since it has that whole flavor prioritisation) and other software has the same behaviour. So could it be related to (probably improper) detection whether there is an image on the clipboard? If that is implemented by checking clipboard.ContainsImage then that is only true if a bitmap was put on it (with SetImage). 

For now the checkbox works and, given time, I will dig deeper in the TB code to find out.

**Comment by Lakritzator** [comment]
I was so convinced I didn't make mistakes in my code, that I forgot to check the installation files.
Due to some new logic, I needed to add a few dll files, thus causing issues in that area.

I fixed this, please test but do reset the settings back to before (Device Independent Bitmap & PNG) 1.3.239 found [here](https://github.com/greenshot/greenshot/releases)

**Comment by ypcyc** [comment]
With "Device Independent Bitmap" & "PNG" both checked it's working.

PS Can you please make same "releases url" target when there is a notification about newer version (maybe in release candidate version only). Currently it's pointing to Homepage downloads url where only version from 2017 is available. Or maybe you can add link to "Releases" in "Downloads".
When I switched to Greenshot from previous screen capturing program this made me think Greenshot was not updated since 2017 :)

**Comment by Lakritzator** [comment]
@ypcyc Thanks for the feedback. It's a bit more complicated than that, the feed is actually updated but only if I update the website. This is on purpose, otherwise people get "update" notices all the time. Also, Greenshot was not "updated" (released) since 2017, you are running not completely tested versions of Greenshot.

**Comment by Frank071** [comment]
@Lakritzator installed 239, removed BMP setting and the behaviour is again as expected (at least in Thunderbird, don't have the environment of the OP).

**Comment by dingolino** [comment]
Hi,
I am traveling right now, with limited possibilities to test. But it looks like that the latest version is working also nicely for HCL notes, without the expert Modus.

Best regards
Claus



Am 8. Februar 2022 14:16:07 MEZ schrieb Robin Krom ***@***.***>:
>I was so convinced I didn't make mistakes in my code, that I forgot to check the installation files.
>Due to some new logic, I needed to add a few dll files, thus causing issues in that area.
>
>I fixed this, please test but do reset the settings back to before (Device Independent Bitmap & PNG) 1.3.239 found [here](https://github.com/greenshot/greenshot/releases)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/greenshot/greenshot/issues/372#issuecomment-1032597449
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Lakritzator** [comment]
Seems to be solved with the most recent builds, closing this.
