### ISSUE TITLE
1.3.239 don´t export to Excel2007 or Word 2007

### ISSUE THREAD

**Issue by WeT-Klb** [greenshot/greenshot#377]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues.

I am not registered to JIRA - so can´t log in there.

**Describe the bug**
Exporting to Micrisoft Word 2007 or Excel 2007 causes Error - Outlook 2007 works flawless

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture a screen
2. Open directly to Microsoft Word
3. Error Message appears

**Expected behavior**
The screencapture should open in Word or Excel
![GreenShot](https://user-images.githubusercontent.com/20600342/153000352-7ea8173b-75f0-47af-8cd2-ddea4e0b80ea.jpg)

**Screenshots**

**Versions (please complete the following information):**
 - Greenshot version
 - Windows version

**Additional context**

**Comment by Lakritzator** [comment]
I'm really sorry, but as Greenshot comes for free I do not have the time and money to support all versions of Office, as with all versions of windows. Especially if they are no longer current, meaning out of support, and Office 2007 is LONG out of support: https://docs.microsoft.com/en-us/lifecycle/announcements/office-2007-end-of-support
I do not have a system with that running, nor I would like to install it somewhere.

Maybe there is something in the log file, which might "hint" on the issue, and makes it possible to fix it due to a very clear error. The one on the screen is not saying a lot...

Here are details on where to find the logs: https://getgreenshot.org/faq/where-can-i-find-greenshots-log-file/

**Comment by Lakritzator** [comment]
P.S. if you are on a personal system, I can understand you do not want to invest but if that is a company PC, I REALLY urge you to update or tell your IT to update. [There is a high risk!](https://www.myce.com/news/microsoft-warns-security-risks-caused-end-office-2007-support-82345/#:~:text=Microsoft%20warns%20of%20security%20risks%20caused%20by%20end%20of%20Office%202007%20support,-By&text=Using%20the%20software%20after%20October,day%20attacks%20in%20recent%20years.)

**Comment by WeT-Klb** [comment]
Hi,

 

thanks für fast reply. I added the log file - maybe you can figure out something.

And yes - I run Office 2007 on a private computer ;-)

**Comment by Lakritzator** [comment]
So I remember again, Greenshot works with Office 2013 and later, which means it's linked against the Office version 15.0.0.0 dlls. This is what the error is. I cannot support older versions of Office, so you will have to stay with Greenshot 1.2 or upgrade office (which wouldn't hurt the security of your system) 

I'm not sure why it works with Outlook though... maybe because it just uses the MAPI (Mail API) as a fallback.

```
 System.IO.FileNotFoundException: Die Datei oder Assembly "office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
File name: 'office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'
   at Greenshot.Plugin.Office.OfficeExport.WordExporter.InsertIntoNewDocument(String tmpFile, String address, String tooltip)
   at Greenshot.Plugin.Office.Destinations.WordDestination.ExportCapture(Boolean manuallyInitiated, ISurface surface, ICaptureDetails captureDetails) in D:\a\1\s\src\Greenshot.Plugin.Office\Destinations\WordDestination.cs:line 148
```

I understand that doesn't help you, but I hope you understand that if I support everything which ever was, I would not be able to move forward EVER. 🤷 

So I have to close this, with "wont fix".
