### ISSUE TITLE
Documentation for OCR Support 404 error

### ISSUE THREAD

**Issue by simon-Leary42** [greenshot/greenshot#381]
The JIRA issue system won't let me make an account, I click log in and it refreshes the page and changes nothing. 
I don't care enough to figure that out so I'm leaving it here.

This link: https://getgreenshot.org/faq/how-can-i-use-greenshot-for-ocr/
Says that to enable OCR, one should first go to this link: https://support.microsoft.com/kb/982760
and follow method 2.
Method 2 says that one should first go to this link: http://www.microsoft.com/download/en/details.aspx?displaylang=en&id=21581
which is a 404 error.

Do methods 1 and 3 work as well, or only method 2?

**Comment by Lakritzator** [comment]
No problem about the JIRA system, I can related to if things do not work.

Sorry to see that Microsoft removed their downloads, due to licensing we cannot provide those to you.
That said, the technology mentioned is extremely old and installing that doesn't make you very happy.

We have added newer OCR support on that what is becoming our new release, but it only works on Windows 10 and has to be a build from at least 2019 to get it. You can find it [here](https://github.com/greenshot/greenshot/releases), but it's work in progress. You also need to go through a few hoops during the installation (do you want to keep it, you really want to install etc...) due to the fact that is hasn't been signed yet. As long as you install Greenshot with the Windows 10 plugin the OCR functionality should be included.

It's currently only about putting the captured part through OCR, and placing it on the clipboard. There is no other functionality, but we have more on the roadmap.

Hope this helps?

**Comment by Lakritzator** [comment]
Closing this, as I think everything is said which needs to be said and there was no response anymore.
