### ISSUE TITLE
Unable to Paste into Microsoft Teams (from v1.3.244)

### ISSUE THREAD

**Issue by leewilmott** [greenshot/greenshot#392]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

I have logged this here because it discusses an issue with a version of Greenshot that is in pre-release.

**Describe the bug**
I am unable to copy an image from Greenshot and paste it into a chat thread in Microsoft Teams.

**To Reproduce**
Example steps to reproduce the behaviour:
1. Capture '....'
2. Open Editor.
3. Press the "Copy image to clipboard" button.
4. Paste into Microsoft Teams (nothing appears)

**Expected behaviour**
If I press 'copy' from Greenshot then I expect to be able to paste it into a chat thread in Microsoft Teams.

**Versions (please complete the following information):**
 - Greenshot version 1.3.244
 - Windows 10 Enterprise 21H2 (19044.1586)

**Comment by Christian-Schulz** [comment]
You can fix the problem by changing the clipboard format to "Windows Bitmap".

![image](https://user-images.githubusercontent.com/32000301/159790112-aea29ceb-0248-49b4-a9be-be73a1779be5.png)

**Comment by Lakritzator** [comment]
This "should" not be needed, I actually tested that with another version which already had the newest clipboard stuff:
https://github.com/greenshot/greenshot/issues/374#issuecomment-1032619784

Only the formats mentioned there should be enabled... either a new error came up, or I didn't test it correctly, because I cannot get it working either. will check it out. As a workaround do what @Christian-Schulz said.

**Comment by Lakritzator** [comment]
Try 246, the issue with 244 should be fixed: https://github.com/greenshot/greenshot/releases

**Comment by Christian-Schulz** [comment]
have tried it, problem solved for me
