### ISSUE TITLE
What would it take to build on Mono?

### ISSUE THREAD

**Issue by thiagocmoraes** [greenshot/greenshot#5]
I've read the FAQ which says that a Mac/Linux version is unlikely, but considering that this project doesn't have many external dependencies, I'm investigating wheter I can build it on mono. Has anyone tried this already?

Just importing the solution into Mono Develop gets me some configuration errors that I need to explore, but looking at the build scripts, it seems like the biggest hurdles would be to make the tooling such as `innosetup`, `PortableApps.comInstaller` etc to work. 

Is there any outstanding blocking issue to proceed with this that you are aware of? I'd love to work on this but I know very little about .NET in general, so some tips could help me a lot in evaluating the feasibility of this work. 

Any pointers?

**Comment by Lakritzator** [comment]
Currently it would not be possible to build it on mono, as Greenshot is **very ** tightly integrated into the Windows OS. The way we use the hotkeys and capturing would most likely NOT work on Mono, so we would first need to make it possible to replace these parts with different implementations.

I am working very hard on modularizing Greenshot, where as a result it should be easier to replace parts with an implementation which might work on Mono. By making the parts "stand alone", it's also easiert to test only this part. Currently in Greenshot 1.2 is just a bunch of Code where one small thing will make it fail and you will have no idea where the problem lies or how to fix this.

The current state of making Greenshot more modular:
- a module for loading (and starting) add-ons: [Dapplo.Addons](https://github.com/dapplo/Dapplo.Addons)
- a module for configuration and language support : [Dapplo.Config](https://github.com/dapplo/Dapplo.Config)
- a module for making Http calls the same for all addons [Dapplo.HttpExtensions](https://github.com/dapplo/Dapplo.HttpExtensions) this prevents that one writes a need "plug-in" (addon, extension, whatever you call it) which doesn't work through a proxy when other parst of Greenshot do
- a module for the Jira API, [Dapplo.Jira](https://github.com/dapplo/Dapplo.Jira) which will be used in the plugin
- a module for the native Windows logic, like finding the location etc, [Dapplo.Windows](https://github.com/dapplo/Dapplo.Windows)
- And now I will start working on the plug-ins/addons itself, so they get their own repos.

Everything is work in progress, and changing constantly...


Inno-Setup is our installer builder, PortableApps is another, both are not needed to make a working Greenshot. It would work fine, just by having the resulting files in a directory.

But like I said, it would take a LOT of time to "port" the current Greenshot to Mono. Another problem is that I am changing currently so much (see develop branch) that you would be porting a moving target. Besides, I want to see where Microsoft is going with the new .NET core..

Currently it would not be feasable, or maybe that's wrong as everything is possible, I would advice against it... At least wait a few months until I have refactored the project.

P.S.
One person of our Team is working on a prototype for Mac, we don't know if we ever release it but just so you know the final word is not said. Besides time, the biggest problem with a Mac version, is money... I don't want to spend > 1000€ for a laptop, which is money we might never see back... only 1 of our team which exists of 3 people has a Macbook...

**Comment by Lakritzator** [comment]
The modules that I recently created alone are already > 21.000 lines of code, as can be seen here: https://www.openhub.net/p/dapplo

If you have little knowledge of .NET... it's a lot to swallow :)

**Comment by Lakritzator** [comment]
One last thing... my biggest problem with Mono would be the UI.
We are in the process of removing all Windows.Forms code, and changing to WPF, which is already a lot of work. If we also need to write a new UI for Mono :(

**Comment by thiagocmoraes** [comment]
Understood. Thanks for the thorough answer. This is a bummer to me because I love greenshot a lot and would love to use a few features from it, but Mac support is a must for me. As this is quite a big overhaul, I'll let it pass and check again in a few months. Using this as an opportunity to learn .NET and Mono at once seems too big of a leap :)

**Comment by Lakritzator** [comment]
Like I said, Mac might happen... still it would never be the same as Greenshot on Windows, not laying any weight on if this is good or bad... just different as it would have a different code base (no reused) and it's based on a different platform (different behavior).

We considered Xamarin, a very popular "platform" for developing applications for multiple platforms, but the pricing is something a bit out of our league... If I understood it correctly it would be 1000$ per developer (3x) per year... Than we need an Apple Store account, and the mac books... that put together and subtracted from our yearly "earnings" from donations, would be a negative amount... 
Okay, we might earn a bit more by selling the application... but this again would lower the donations...

And the work that needs to be made before it works...

**Comment by Lakritzator** [comment]
Just a small update.

In the mean time I already made some of the components for Greenshot available for the .NET Core (Linux, Mac etc), unfortunately I am far away of having a running Greenshot as there is no UI or capture logic.

1. Logging
2. HTTP extensions (to connect to cloud services etc)
3. Clients for Jira and Confluence

Further more my colleague is working on a Mac version, but this is native.

**Comment by Lakritzator** [comment]
We are removing the issues on github, as most people don't read and create feature request or report bugs here... and we already have an issue tracker. Just so you know.

https://greenshot.atlassian.net
