### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by psmoros** [greenshot/greenshot#504]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@securecodeninja) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by bscharff** [comment]
The correct place to submit vulnerabilities is here.

**Comment by jklingen** [comment]
I also added a [SECURITY.md](https://github.com/greenshot/greenshot/blob/release/1.3/SECURITY.md) file as suggested, pointing out where to report security issues. So I think this issue can be closed.

So far there's not report in there, so I assume the issue you wanted to report is the one about .greenshot files I mentioned above. Otherwise, feel free to create a report.

Thanks a lot.

**Comment by AkechiShiro** [comment]
Thanks a lot @jklingen for having put the security policy in place.
