### ISSUE TITLE
http://getgreenshot.org/ is breached with malware inside ads

### ISSUE THREAD

**Issue by bgoodr** [greenshot/greenshot#549]
### Summary

I was instructing someone on how to download Greenshot using the downloads buttons on http://getgreenshot.org/ (explicitly linked into https://github.com/greenshot/greenshot so this must be intentional) but that someone just happened to *not* be using an adblocker as I use. Had I not been watching this someone do the installation, they would have gotten tricked into clicking on malware ads redirecting his browser window to malware websites (see PoC details below). I had to stop this someone from proceeding as I just so happened to be paying acute attention to his every move!

I then went to my own browser on my own machine and retested navigating to http://getgreenshot.org/ and found that it was "ok" in the sense that I could find the truthful download button, and not get fooled by fake download buttons.

Please answer all of these questions:

1. Is it implied that everyone should be using adblockers to download the binary stable release? Surely that must not be your intent, is it?
2. Why then is http://getgreenshot.org/ the only place that one can find the stable releases? Is there some reason why http://getgreenshot.org/ has to be the only place to find them, or is there some way to access the current most recent release directly from within github.com without risk of fake download buttons popping up?

### Details

See PoC below.

### PoC

This PoC was done on a Windows 11 host using Google Chrome Version 127.0.6533.100 (Official Build) (64-bit), but I also saw this on a different browser (species and manufacturer not known at the time of this writing).

Navigate first to http://getgreenshot.org/, then turn off ad blockers on that page only (this is a *critical* step to do). 

See the following screenshot that shows the malware ads that have **HUGE DOWNLOAD BUTTONS** that are so huge as to trick your potential users into installing malware, or if they get lucky, only download some special browser but who can tell what is truth and falsehood here, can you? I certainly cannot:

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/de6433f1-8d58-449e-a8bc-5018d5f2eecd">

*But wait, there's more con jobs afoot!*  If you wait for some time interval (presumably while you are figuring out which of those fake download buttons to click on), the malware ads tries to trick the user *again* by some type of popover ad that also blurs out the rest of the otherwise legitmate page, showing this:

<img width="1228" alt="image" src="https://github.com/user-attachments/assets/cfbaf756-56e2-4d8e-b20c-24b1138ad7d3">

### Impact

All users that do not use an ad blocker affected.

**Comment by jklingen** [comment]
Thanks for your feedback.

"breached with malware" is a little blatant, maybe. There is no breach - what you see is advertisements (which are absolutely inappropriate, yes). I don't know what the advertised software is about, but I'd expect Google to have mechanisms in place to check advertisers on their platform. 

I fully agree with you that the ads you witnessed are misleading and should be removed as soon as possible. They're as annoying for us as they are for you. Whenever we see them, we head over and block them. Sometime later, maybe, similar ads appear again ☹️ 

The problem is: we don't necessarily see the same ads that other people see. Google displays different ads based on location, interests etc.

The good thing is: everybody can help to get rid of these annoyances and make the web a better place. Google offers a [form for reporting inappropriate apps](https://support.google.com/google-ads/answer/7660847), it is also possible to quickly send ad feedback by clicking the small blue "x" button in the top-right corner of each ad.

We'll happily check and block what we see. If anyone else sees ads like these, please report them as inappropriate/misleading to Google.

**Comment by bgoodr** [comment]
I do not understand why it's not possible to instead  have a link inside the GitHub read me that points to the staple releases, as that should be fairly straightforward to do inside GitHub itself. That seems to be the least expensive fix to the malware infection problem, instead of requiring your users to provide the most expensive expenditure of all, their attention spans, in filtering out the so-called good ads from the malware ads.

**Comment by JamesPratt-LWL** [comment]
Why not just redirect the site to the Github repo.... AKA KISS. (?)

**Comment by jklingen** [comment]
@bgoodr Please stop framing this as compromise.  Google's adevertising platform delivers inappropriate ads. We'll get rid of them. Anyone can help. That's the story.

> I do not understand why it's not possible to instead have a link inside the GitHub read me...

For most people, a custom website is more convenient than the Github platform. Everyone else is free to download the releases from there. (I think it is safe to assume that people coming from the README in the repository file belong to the latter category.)
By the way, the website is also running on GH and references the releases on GH.

Users of a free software tool should consider reporting inappropriate ads to the advertising platform directly. It helps the maintainers to get rid of them quickly, it helps Google to understand what people regard as inappropriate and it helps fellow users who don't have to see these ads in the future. Everyone wins, except the questionable advertiser.

> requiring your users to provide the most expensive expenditure of all, their attention spans

If more users (and companies) would provide other expenditure on open source software, we could afford to put more time into this project and run an ad-free website. Please keep in mind that Greenshot is ran by a few folks in their few spare time.


Anyway, thanks for reporting this issue so that we can take action. We also appreciate anyone helping by reporting ads like these to Google.

**Comment by bgoodr** [comment]
I formally request that the readme have a direct link that drives directly to the webpage or folder on github that provides links to download the installers directly without ads. Why is that not possible? Is it technically impossible to do so?  

I am not intending any form of "compromise", but negating any possibility to have the subset of users who are cautiousely avoiding any small element of cybercrime to infect their hosts due to accidental clicks upon the malware ads, by my request in the prior paragraph.

**Comment by jklingen** [comment]
The part about "compromise" probably got lost in translation. My intention was to emphasize that our website is not *compromised* (breached, hacked, infected, ...) in any way and I'd prefer if you didn't use this vocabulary because it scares people more than it should. These things are still just advertisements which take you to a different website, offering to download another product which is not related. (Again, I agree the style of these ads is inappropriate and we're taking action.)

I just added an [FAQ entry about reporting inappropriate ads](https://getgreenshot.org/faq/where-should-i-report-inappropriate-advertisements/), and also links to the [readme file](https://github.com/greenshot/greenshot/blob/release/1.3/README.md), where people can find releases on Github or our website.

**Comment by petervandivier** [comment]
The ads on the [download page](https://getgreenshot.org/downloads/) in particular are still incredibly spammy. From the [FAQ](https://getgreenshot.org/faq/where-should-i-report-inappropriate-advertisements/):

> Whenever we see them we head over and block them.

The screencap from the OP over a year ago has an ad for "Wave browser" and I'm still seeing these (among others) today. Given this appears to be a systemic issue, it really feels like a bit of a deeper dive into your Adsense settings might be warranted. I don't know how much it would cost you but if possible it might be prudent to disable ads altogether on the downloads page at least if no other mitigations present themselves.
