### ISSUE TITLE
Automatically copy changes in screenshot to clipboard

### ISSUE THREAD

**Issue by dnngll** [greenshot/greenshot#8]
.. as seen in Windows Snipping Tool would be a great addition to an otherwise awesome program.

Description: Just taking a screenshot without editing it is fine - program can be set up to automatically copy the screenshot to clipboard. However, if I alter the picture these changes are not "updated" (overwritten) in the clipboard and I have to do it manually (CTRL-SHIFT-C).

Thanks in advance,

Dennis : )

**Comment by Lakritzator** [comment]
This is not our primary ticket system, and only for developers... so we don't respond quickly to tickets that are not code related. This is mentioned when you create a ticket, in the "guidelines for contributing" shown when creating a ticket. Nobody seems to read this, I might need to remove the issues from the project... :(
https://github.com/greenshot/greenshot/blob/develop/CONTRIBUTING.md

This might be an easy feature, if you need it please report it in our feature tracker. (as mentioned on our website http://getgreenshot.org)

I personally don't care much about the clipboard, this is one of the worst implemented ways to have applications "communicate" with each other... So this is not a feature I would use myself, and it also won't be a feature which we would enable by default.... the problem is that when someone would copy something to the clipboard in between and change something in the editor it's gone...

Actually it might not be so easy, yes maybe it's easy to implement, but it might confuse people...

Like I said, wrong place to discuss this...
